config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :contacts, only: [:create, :new]
  get 'static_pages/about'
  root 'items#index'
  resources :item_carts, only: [:index, :show, :create]
  resources :carts, only: [:index]
  resources :users, only: [:show], path: :mon_profil do 
    resources :avatars, only: [:create]
  end
  post 'create', to: 'item_carts#create', as: 'create_item_cart'

  resources :items, only: [:index, :show], path: :potit_chat

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :item_carts
  has_many :items, through: :item_carts

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :email, 
    :presence => :true,
    :format => { 
      :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      :message => "must be a valid email address"
    }
  validates :message, :presence => :true
  validates :object, :presence => :true
  validates :name, :presence => :true
end

app/models/create_item_orders.rb
class CreateItemOrder < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true, length: { in: 3..45 }
  validates :description, length: {maximum: 200}
  validates :price, presence: true 
  validates :image_url, presence: true

  has_many :item_carts
  has_many :carts, through: :item_carts
  has_many :item_orders
  has_many :items, through: :item_orders
end

app/models/item_cart.rb
class ItemCart < ApplicationRecord
  belongs_to :cart
  belongs_to :item

end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :item_orders
  has_many :items, through: :item_orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_one :cart, dependent: :destroy
  has_one :cart_id, through: :cart
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :authenticate_user!
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = params[:total].to_i

    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          name: 'Rails Stripe Checkout',
          amount: @total,
          currency: 'eur',
          quantity: 1,
          
        },
      ],
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    respond_to do |format|
      format.js #renders create.js.erb
    end
  end

  def cancel
    redirect_to item_cart_path(current_user.id)
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  def index
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      ContactMailer.general_message(@contact).deliver
      ContactMailer.personnal_message(@contact).deliver
      redirect_to root_path, notice: "Message envoyé !"
    else
      render :new
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :object, :message)
    end
  end

app/controllers/item_carts_controller.rb
class ItemCartsController < ActionController::Base
  include ApplicationHelper
  layout "application"
  before_action :authenticate_user!, only: [:create, :show]

  def index
    @items_of_cart = ItemCart.all
  end

  def show
    @current_cart = current_user.cart
    @items = @current_cart.items
    @total = total(@items)
  end

  def create

    @item = Item.find(params[:item_id])
    @cart = current_user.cart
    @items_of_cart = ItemCart.new(item: @item, cart: @cart)

    if @items_of_cart.save
      flash[:success] = "Bravo la photo n°#{@item.id} a bien été ajouté au panier"
    else
      flash[:alert] = "Echec de création de l'objet due a:\n 
                      #{@items_of_cart.errors.full_messages.to_sentence}"
    end
    redirect_to root_path
  end

  private

  def total(items)
    total = 0
    items.each do |item|
      total += item.price
    end
    return total
  end

  def item_carts_params
    @item_cart.permit(:cart_id, :item_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ActionController::Base
  layout "application"

  def index
    @items = Item.all
    @item = @items.sample

  end

  def show
    
    respond_to do |format|
      @item = Item.find(params[:id])
      format.html {render 'show'}
      format.js {}
    end
  end

  def create
    puts "\n\nITEM = #{@item} #{item} #{params[:item]}\n\n"
    @cart = current_user.cart
    @order = Order.new(item: item, cart:@cart)
    render root_path(locals: { :object_created => @order, :success_message => "BRAVO JJJJJJJ" })
  end

  private 

  def items_params
    @item.permit(:title, :description, :price, :image_url)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ActionController::Base
  layout "application"
  before_action :authenticate_user!, only: [:create]

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
  end
  def create
    @item = Item.find(params[:item_id])
    @cart = current_user.cart
    @order = Order.new(item: @item, cart: @cart)
    if (@order.save)
      flash[:success] = "Bravo la photo n°#{@item.id} a bien été ajouté au panier"
      render 'items#index'
    else
      redirect_to root_path, :locals => {:sucess_message => nil, :message_failure => "Nous n'avons pas réussi à créer  pour la (ou les) raison(s) suivante(s) :"}
    end

  end

  private 

  def orders_params
    @order.permit(:cart_id, :item_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice" then "alert alert-info"
      when "success" then "alert alert-success"
      when "error" then "alert alert-warning"
      when "alert" then "alert alert-danger"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_id(order)
    items_of_cart.cart.user_id
  end 
end

app/views/item_carts/show.html.erb
  <div class="container-fluid>
    <div class="container">
    <div class="row">
  <% @items.each_with_index do |item, index| %>
    <div class="col-md-3 d-flex align-items-stretch">
      <div href="#" class="card card-product-grid mt-4">
        <a href="/potit_chat/<%=item.id%>"><%=image_tag item.image_url, class:"img-thumbnail"%></a>
        <figcaption class="info-wrap text-center">
          <%= link_to item.title , item_path(item.id) %>
          <div class="price mt-1 text-center"><%= item.price %>€ </div> <!-- price-wrap.// -->
        </figcaption>
      </div>
      </div><!-- col.// --> 
  <%end%>
  <div class="bd-example d-flex mt-5 justify-content-center">
    <%= button_to "Montant total : #{@total} € TTC", checkout_create_path(total: @total * 100), class:"btn btn-info btn-lg px-5", remote: true%>
    </div>
  </div>

app/views/items/_description.html.erb
        <a href="/potit_chat/<%=item.id%>" class="img-wrap"> <%= image_tag item.image_url, class:"img-thumbnail w-100"%> </a>
        <figcaption class="info-wrap text-center">
          <%= link_to item.title, item_path(item.id), remote: true%>
          <div class="info-wrap"><%=item.description%></div>
          <div class="price mt-1 text-center"><%= item.price %>€ </div> <!-- price-wrap.// -->
        </figcaption>
        <%= link_to "Acheter", create_item_cart_path(:item_id => item.id), { method: "post", action: "create", class:"btn btn-warning" } %>

app/views/items/_imageindex.html.erb
<div class="row mt-3">
  <% @items.each_with_index do |item, index| %>
    <div class="col-md-3">
      <div href="#" class="card card-product-grid mt-4" id="description">
        <a href="/potit_chat/<%=item.id%>" class="img-wrap"> <%= image_tag item.image_url, class:"img-thumbnail w-100"%> </a>
        <figcaption class="info-wrap text-center">
          <%= link_to item.title, item_path(item.id), remote: true%>
          <div class="price mt-1 text-center"><%= item.price %>€ </div> <!-- price-wrap.// -->
        </figcaption>
        <%= link_to "Acheter", create_item_cart_path(:item_id => item.id), { method: "post", action: "create", class:"btn btn-warning" } %>
      </div>
    </div> <!-- col.// --> 
  <%end%>
</div><!-- container // -->

app/views/items/_showitem.html.erb
<!DOCTYPE html>
<html>

<body>
  <div class="container">
    <br>
    <br>
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <div class="img-big-wrap">
           <%=link_to image_tag (@item.image_url), class:"img-profile" %>
         </aside>
         <main class="col-md-6 border-left">
          <article class="content-body">
            <br>
            <h2 class="title"><%= @item.title %></h2>


            <div class="mb-3"> 
              <var class="price h4"><%= @item.price %> €</var> 
            </div> 

            <p><%= @item.description %></p>

            <hr>
            <div class="row">
              <div class="form-group col-md flex-grow-0">
              </div> 
            </div> 
            <a href="#" class="btn  btn-primary"> Ajouter au panier </a>
            <br>
          </article> 
        </main> 
      </div> 
    </div> 
  </div>
</body>
</html>

app/views/items/index.html.erb
<section class="bgimage">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12 text-center mt-5">
      <div class="container-fluid">
        <h1 class="hero-title">Bienvenue sur votre nouveau site préféré !</h1>
        <h4 class="text-secondary hero-subtitle">Découvrez, achetez et collectionnez des photos de chats par milliers !</h4>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-name  padding-y-sm">
  <div class="container">
<p id="notice"><%= notice %></p>
  <%= render 'imageindex'%>
  </div>
</section>

app/views/items/show.html.erb
<!DOCTYPE html>
<html>
<body>

  <div class="container">
    <div class="row">
      <br><br><br>

      <%= render 'showitem', item: @item %>

      <br>
    </div>
  </div>
</body>
</html>

app/views/items/show.js.erb
document.getElementById("description").innerHTML = "<%= j render "description", item: @item %>"

app/views/orders/_orderindex.html.erb
<div class="row mt-4">
<% @orders.each do |order|%>
	<div class="col-md-4">
		<div href="#" class=" mt-4 d-flex-center">
				<%= image_tag order.item.image_url, class:"img-index"%>
			<!-- price-wrap.// -->
		</div>
		<a href="items/<%=order.item_id%>"><%= order.item.title%></a> 
	</div> <!-- col.// -->
	   <%end%>
</div><!-- container // -->