config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :contacts, only: [:create, :new]
  get 'static_pages/about'
  root 'items#index'
  resources :item_carts, only: [:index, :show, :create]
  resources :carts, only: [:index]
  resources :users, only: [:show], path: :mon_profil do 
    resources :avatars, only: [:create]
  end
  post 'create', to: 'item_carts#create', as: 'create_item_cart'

  resources :items, only: [:index, :show], path: :potit_chat

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_one :cart, dependent: :destroy
  has_one :cart_id, through: :cart
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
 # before_action :configure_sign_up_params, only: [:create]
 # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

   #POST /resource
   def create
     super
     if (current_user)
       @cart_to_create = current_user.build_cart
       @cart_to_create.save
     end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

   #GET /resource/sign_in
   def new
     super
   end

   #POST /resource/sign_in
   def create
     super
     @cart_to_create = current_user.build_cart
     @cart_to_create.save
   end

   #DELETE /resource/sign_out
   def destroy
     #@current_user = User.find(current_user.id)
     @cart_to_destroy = current_user.cart
     if (@cart_to_destroy)
       @cart_to_destroy.destroy
     end
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_id(order)
    items_of_cart.cart.user_id
  end 
end

app/views/users/_showuser.html.erb
      <body>
      <div class="container">
      <div class="card">
       <div class="row no-gutters">
      <div class="card-body">
    </div>
      <div class="row">
        <div class="col-md-4">
          <div class="card-body">
          <%if @user.avatar.attached?%>
            <%= image_tag @user.avatar, alt: 'avatar', class:"avatar shadow"%>
            <h5 class="text-center mt-3">Mettre à jour l'avatar</h5>
            <hr>
          <%else%>
            <p>Pas d'avatar défini</p>
            <p>Choisir un avatar ?</p>
            <%end%>
              <%= form_tag user_avatars_path(@user), multipart: true do %>
              <%= file_field_tag :avatar , class:"form-control btn btn-secondary mb-3"%>
              <%= submit_tag "mettre à jour", class:"btn btn-secondary form-control" %>
            <% end %>
            <hr>
          <h5 class="card-text text-center">Adresse mail :</h5>
          <h5 class="card-text text-center"><%= @user.email %></h5>
          <%= link_to "Editer le profil" ,edit_user_registration_path, class:"btn btn-danger form-control" %>
        </div>
    </div>
      <div class="col-md-8">
      <div class="card-body">
        <h3 class="card-text text-center">Mes commandes : </h3>
        <br>
        <p class="card-text description"><p class="card-text"></p>
        <% if current_user.id == params[:user_id] %>
          <%= render 'orders/orderindex'%>
          <%else%>
          <p>Aucune commande effectuée</p>
          <%end%>
      </div>
      </div>
      
  </div>
    </div>
      </div>
         <div class="card-footer bg-primary text-light">
      <caption>Profil crée le <%=@user.created_at%></caption>
      </div>
      </div>
      <br>
</body>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'showuser' %>