config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :contacts, only: [:create, :new]
  get 'static_pages/about'
  root 'items#index'
  resources :item_carts, only: [:index, :show, :create]
  resources :carts, only: [:index]
  resources :users, only: [:show], path: :mon_profil do 
    resources :avatars, only: [:create]
  end
  post 'create', to: 'item_carts#create', as: 'create_item_cart'

  resources :items, only: [:index, :show], path: :potit_chat

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :item_carts
  has_many :items, through: :item_carts

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :email, 
    :presence => :true,
    :format => { 
      :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      :message => "must be a valid email address"
    }
  validates :message, :presence => :true
  validates :object, :presence => :true
  validates :name, :presence => :true
end

app/models/create_item_orders.rb
class CreateItemOrder < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true, length: { in: 3..45 }
  validates :description, length: {maximum: 200}
  validates :price, presence: true 
  validates :image_url, presence: true

  has_many :item_carts
  has_many :carts, through: :item_carts
  has_many :item_orders
  has_many :items, through: :item_orders
end

app/models/item_cart.rb
class ItemCart < ApplicationRecord
  belongs_to :cart
  belongs_to :item

end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :item_orders
  has_many :items, through: :item_orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_one :cart, dependent: :destroy
  has_one :cart_id, through: :cart
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :authenticate_user!
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = params[:total].to_i

    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          name: 'Rails Stripe Checkout',
          amount: @total,
          currency: 'eur',
          quantity: 1,
          
        },
      ],
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    respond_to do |format|
      format.js #renders create.js.erb
    end
  end

  def cancel
    redirect_to item_cart_path(current_user.id)
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  def index
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      ContactMailer.general_message(@contact).deliver
      ContactMailer.personnal_message(@contact).deliver
      redirect_to root_path, notice: "Message envoyé !"
    else
      render :new
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :object, :message)
    end
  end

app/controllers/items_controller.rb
class ItemsController < ActionController::Base
  layout "application"

  def index
    @items = Item.all
    @item = @items.sample

  end

  def show
    
    respond_to do |format|
      @item = Item.find(params[:id])
      format.html {render 'show'}
      format.js {}
    end
  end

  def create
    puts "\n\nITEM = #{@item} #{item} #{params[:item]}\n\n"
    @cart = current_user.cart
    @order = Order.new(item: item, cart:@cart)
    render root_path(locals: { :object_created => @order, :success_message => "BRAVO JJJJJJJ" })
  end

  private 

  def items_params
    @item.permit(:title, :description, :price, :image_url)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ActionController::Base
  layout "application"
  before_action :authenticate_user!, only: [:create]

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
  end
  def create
    @item = Item.find(params[:item_id])
    @cart = current_user.cart
    @order = Order.new(item: @item, cart: @cart)
    if (@order.save)
      flash[:success] = "Bravo la photo n°#{@item.id} a bien été ajouté au panier"
      render 'items#index'
    else
      redirect_to root_path, :locals => {:sucess_message => nil, :message_failure => "Nous n'avons pas réussi à créer  pour la (ou les) raison(s) suivante(s) :"}
    end

  end

  private 

  def orders_params
    @order.permit(:cart_id, :item_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice" then "alert alert-info"
      when "success" then "alert alert-success"
      when "error" then "alert alert-warning"
      when "alert" then "alert alert-danger"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_id(order)
    items_of_cart.cart.user_id
  end 
end

app/views/layouts/_flash_message.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> text-center">
      <a href="#" data-dismiss="alert" class="close"></a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted mt-5">
      <!-- Section: Social media -->
      <section
      class="d-flex justify-content-center justify-content-lg-between border-bottom">
    </section>
    

    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Nos réseaux sociaux
            </h6>
            <p>
              <a href="#!" class="text-reset">Facebook</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Twitter</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Instagram</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Pinterest</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Nos services
            </h6>
            <p>
              <%= link_to "Liste des photos", items_path, class:"text-reset"%>
            </p>
            <%if user_signed_in?%>
            <p>
              <%= link_to "Mon panier", item_cart_path(current_user.id), class:"text-reset"%>
            </p>
            <%else%>
            <%end%>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            
            <i class="fas fa-envelope me-3"></i>
            pussyfans@yopmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i>+33 77 55 64 84</p>
          <p>
              <%= link_to "Formulaire de contact", new_contact_path, class:"text-reset"%>
            </p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

</footer>



</html>

app/views/layouts/_navbar.html.erb
<header class="section-header">
<nav class="navbar navbar-default navbar-expand-lg bg-white fixed-top">
<div class="container">
  <a href="/" class="navbar-brand"><img src="https://res.cloudinary.com/dcmcouvju/image/upload/v1623256131/logo_rybibq.png" alt="logo PussyFans" class="w-25"></a>
      <ul class="navbar-nav ml-auto mr-sm-2 mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to "Accueil", root_path, class:"text-white btn btn-info" %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "A propos", static_pages_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "Contact", new_contact_path, class:"nav-link"%>
        </li>
            <li class="nav-item me-4">
          <%= link_to "S'inscrire", new_user_registration_path, class:"btn btn-secondary text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class:"btn btn-info text-white" %>
        </li>
      </ul>
    </div>
</nav>
</header>
<br /><br /><br /><br /><br /><br />

app/views/layouts/_object_handle_message.html.erb
<% if local_assigns[:object_created].errors.any? %>
  <div class="alert alert-danger">
    <p><%= local_assigns[:message_failure] %></p>
    <ul>
      <% object_created.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div class="alert alert-sucess">
    <p><%= local_assigns[:success_message] %></p>
  </div>
<% end %>

app/views/layouts/_usernav.html.erb
<header class="section-header">
<nav class="navbar navbar-main navbar-expand-lg bg-white fixed-top">
  <div class="container">
  <a href="/" class="navbar-brand"><img src="https://res.cloudinary.com/dcmcouvju/image/upload/v1623256131/logo_rybibq.png" alt="logo PussyFans" class="w-25"></a>
      <ul class="navbar-nav ml-auto mr-sm-2 mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to "Accueil", root_path, class:"text-white btn btn-info" %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "A propos", static_pages_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "Contact", new_contact_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Mon Profil", user_path(current_user.id), class:"nav-link" %>
        </li>
            <li class="nav-item me-4">
          <%= link_to "Deconnexion", destroy_user_session_path, method: "delete", class:"btn btn-secondary text-white" %>
        </li>
         <li class="nav-item d-flex">
           <%= link_to  item_cart_path(current_user.id), class:"btn btn-primary me-3" do %>
                <i class="fas fa-shopping-basket"></i>
            <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>
<br /><br /><br /><br /><br /><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PussyFans</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/82779c9172.js" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
  <%if user_signed_in? %>
    <%= render "layouts/usernav" %>
  <%else%>
    <%= render "layouts/navbar"%>
  <%end%>

  <%= render "layouts/flash_message"%>
    <%= yield %>
  <%= render 'layouts/footer' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="javascripts/index.js"></script>
  </body>
  
</html>